### ISSUE TITLE
New fields request for the "Leave" model

### ISSUE THREAD

**Issue by gstam** [dideher/phaistos#27]
Fillipos,

could you please add the following three fields in your "Leave" model. They are necessary to export the document  that grants the sick leave. 

health_committee_protocol     TextField
incoming_protocol			TextField
incoming_date			DateField

**Comment by filipslavik** [comment]
@gstam How we should translate (a label) the `health_committee_protocol` attribute ? "Πρωτόκολλο Υγειονομικής Επιτροπής" ;

**Comment by filipslavik** [comment]
Also, let's please rename `incoming_date` to `incoming_protocol_date`.

**Comment by gstam** [comment]
@filipslavik A valid translation would be "Αριθμός πρωτοκόλλου γνωμάτευσης Α/θμιας Υγειονομικής Επιτροπής" (based on the template they have given me) whiel shorter versions of the label above could be "Αριθμ. Πρωτ. Γνωμά/σης Α/θμιας Υγ. Επιτρ." or "Πρωτόκολλο Γνωμάτευσης Υγ. Επιτροπής".

**Comment by gstam** [comment]
@filipslavik Παράδειγμα τιμής για το παραπάνω πεδίο 2409/2022/09-11-22

**Comment by filipslavik** [comment]
This is a preview of the updated "insert leave" modal dialog : 

![image](https://user-images.githubusercontent.com/4492602/216316403-9f1bf819-38aa-4e3b-8535-82cefb032ca2.png)

**Comment by gstam** [comment]
@filipslavik  Φίλιππε καλύτερα να μπει το "Πρωτόκολλο Γνωμάτευσης Υγ. Επιτροπής"  το άλλο είναι πολύ άσχημο και θα μας την πει και η φιλόλογος.

**Comment by gstam** [comment]
@filipslavik Για τον συγκεκριμένο τύπο άδειας η γνωμάτευση της υγειονομικής επιτροπής έρχεται αρκετά μετά από την άδεια (συνήθως μήνες) και το εισερχόμενο στην ΔΔΕ ακολουθεί χρονικά την γνωμάτευση της υγειονομικής επιτροπής. Φυσικά υπάρχει και το ενδεχόμενο να απορριφθεί η  άδεια αλλά νομίζω ότι δεν μας ενδιαφέρει η συγκεκριμένη περίπτωση γιατί δεν θα υπάρχει άδεια για καταχώριση. Σε κάθε περίπτωση αν θέλεις να μπεις στον κόπο δεν βλάπτει... αλλά θα είναι για τον συγκεκριμένο τύπο άδειας.
