### ISSUE TITLE
Προσθήκη νέου πεδίου στις φόρμες εισαγωγής και τροποποίησης αδειών 

### ISSUE THREAD

**Issue by gstam** [dideher/phaistos#71]
Από το τμήμα αδειών είχαμε το αίτημα να προστεθεί πεδίο με τίτλο «Ημερομηνία εξερχομένου» στις φόρμες δημιουργία και τροποποίησης αδειών στην Φαιστό. 

Στο πεδίο αυτό θα αποθηκεύεται η ημερομηνία έκδοσης της απόφασης της άδειας. 

Θα χρειαστεί να τροποποιηθούν και όλα τα πρότυπα αδειών.

**Comment by slavikos** [comment]
@gstam υπαρχει κάποια σχέση με την ημ/νια "Εισερχόμενου Πρω." ; Δηλαδή να βάλω καποιο validation ; 

![image](https://github.com/dideher/phaistos/assets/491538/e332aea1-8232-43cd-b832-fbf9a443b995)

**Comment by gstam** [comment]
Φίλιππε, ολοκλήρωσα τις μεταβολές που ήθελαν από τις άδειες. Όποτε θέλεις προχωράς στο merge.
